### ISSUE TITLE
EFDesigner category not showing up in Add New item section

### ISSUE THREAD

**Issue by TheMegaMatt** [msawczyn/EFDesigner#1]
Item is still accessible by searching for EFDesigner in the dropdown

**Comment by msawczyn** [comment]
@TheMegaMatt - can you please verify that it's not showing up at (or near) the bottom of the list when the category tree is on "Visual C# Items"? That's what I see in my installation. I agree that it needs to be in another category -- I believe "Data" would be the most appropriate -- and I'll put that on the list to make that happen. But it should be in "Visual C# Items" for you currently.

**Comment by TheMegaMatt** [comment]
@msawczyn  As i said Category wasn't showing up the item is at the end of the list or showing up after a search.

**Comment by TheMegaMatt** [comment]
As of the latest update the Template is not showing again in any category. Testyed on a ASPnet Core app

**Comment by msawczyn** [comment]
@TheMegaMatt Thanks for the update. I see the issue in my Visual Studio installation as well. Since the item lives in "Visual C# / Data", it isn't showing up when you add items to an ASP.NET Core application -- "Data" isn't one of the categories, so it's filtered out. That's true for a "Web Site" project as well, but not for an old-school ASP.NET Web Application, nor for any of the other project types.

Can you please verify that, in your installation, you can add the item in a project type other than ASP.NET Core?

Thanks.

**Comment by msawczyn** [comment]
Accidentally closed.

**Comment by TheMegaMatt** [comment]
Working on a WPF project

Il lun 19 mar 2018, 15:47 Michael Sawczyn <notifications@github.com> ha
scritto:

**Comment by TheMegaMatt** [comment]
Is it not possible to add it to the aspnetcore templates as well?

Il lun 19 mar 2018, 16:15 Michael Sawczyn <notifications@github.com> ha
scritto:

**Comment by msawczyn** [comment]
@TheMegaMatt If it's possible, I don't know how to do it. ASP.NET Core web applications change the meaning of the "ProjectType" and "ProjectSubType" elements in the template definition (https://msdn.microsoft.com/en-us/library/5we0w25d.aspx). Normally, we list the project type as the language (CSharp) and the subtype as the category under that (Data, in this case). The web apps do that in reverse, indicating that the project type is Web and the subtype is the language.

As near as I can tell, there would have to be a separate installation for that, with a separate template ID. While this may be possible, it would be a bit of a pain at this stage of the game. I will certainly add it to the TODO list, though.

The best thing, overall, is to create a library for the persistent entities so that they may be included into multiple projects. Just because the requirements only state that the hosting application is a web app, that doesn't mean that later there may be a console app, or another web app (say, an API app) or even a Windows app that might need to use those entities. Pinching them off into their own library now saves lots of time down the road.

Thanks for helping me work through this! Pointing out the initial problem with the bug surrounding the Pluralization service was a tremendous help (I wouldn't ever have seen that), and I wouldn't have noticed the ASP.NET Core issue for quite a while, I'm sure. I owe you an espresso.

**Comment by TheMegaMatt** [comment]
No problem man love what you doing, I was so sad when they removed the
designer from newer ef, wish they just adapted it! And for the espresso
Illy coffe with sugar xd

Il lun 19 mar 2018, 18:08 Michael Sawczyn <notifications@github.com> ha
scritto:
