### ISSUE TITLE
Current VSIX for Community Edition only - will not install on VS2017 Enterprise

### ISSUE THREAD

**Issue by MHacker9404** [msawczyn/EFDesigner#10]

**Comment by msawczyn** [comment]
Thanks for reporting this. While the VSIX is tagged for Community, anything so tagged should install at that build and higher. That being said, I have had reports of this problem, although I have no idea what the common factor is yet.

A couple of questions for you:

- What version did you try to install?
- Did you get it from GitHub or from the Marketplace?

The two other reports I've had of this problem have been with 1.2.0 on the Marketplace. The same folks were able to get 1.2.0 from GitHub and install without difficulty, so if this is the version you're having trouble with, try getting the [VSIX from GitHub](https://github.com/msawczyn/EFDesigner/releases/download/1.2.0/Sawczyn.EFDesigner.EFModel.DslPackage.vsix). If that works for you, please let me know. I'm really curious why this is happening to a tiny fraction of Visual Studio installations, so I'll be digging into this regardless.

Thanks again for letting me know.

**Comment by MHacker9404** [comment]
I had received notifications that an update was available thru VS2017, but it kept failing.  So I grabbed the latest from the marketplace.  That’s when I got this error.

I’ll grab the release from GitHub and try that.

**Comment by MHacker9404** [comment]
When I grabbed the VSIX from GitHub – there’s a size difference with what comes from the marketplace….
[cid:image001.png@01D42906.AB48BB00]


  1.  Is from GitHub…

**Comment by msawczyn** [comment]
Well, yes there is. That's very disturbing ... it should have grabbed it from GitHub. The version I just downloaded from Marketplace says it's 1.0.4 rather than 1.2.0, although Marketplace lists it as 1.2.0 -- and that's not something I can set; rather, it picks it up from the manifest automatically.

Ok. I've got a bugfix release I need to get out; the problem should be resolved today after I get that out and update Marketplace with the new one. 

It appears I need to contact them and report this as an issue. Thanks for finding this -- it's an enormous help!

When you get a chance, can you let me know if installing the 1.2.0 version from GitHub succeeded? Thanks again.

**Comment by MHacker9404** [comment]
Still had issues ;(

**Comment by msawczyn** [comment]
Marketplace is acting squirrely. I tried reinstalling my extension (on Enterprise) from the Marketplace and got v1.1. <sigh> It installed, but wasn't the version I was expecting.

I just put 1.2.1 up (fixes a few bugs). Can you give that one a go? It's on GitHub as well as the latest release. On a positive note, re-downloading it shows it's the same size as the file I unloaded! Hopefully, this was a passing thing and all is better now.

**Comment by msawczyn** [comment]
Excellent. Ok to close the issue then? Or do you want to do that?

**Comment by MHacker9404** [comment]
I’ll close it :D
