### ISSUE TITLE
Many-to-many best practices in Core?

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner#110]
Hi,

This is not an issue, but some thoughts/questions about the generation of many-to-many associations through the mid entity.

Let's assume that we have a Person and a Language entity, a person speaks 0 to many languages and a labguage is spoken by 0 to many persons. And there is a PersonLanguageRelation entity connecting the two, since there is no many to many in Core. 

The first question is, how would you advise to draw the associations between the primary entities and the mid entity? As unidirectional or bidirectional? 

If unidirectional, please correct me if I've got it wrong, but I have understood that the navigation/reference property, either an Entity or ICollection(Entity), is placed at the source of the association, i.e. at the end with no arrow. And this is the only thing that differentiates the source from the target, i.e. the presence of the reference to the target in the source. 

For my example, I thought it would be enough to know the Persons speaking a Language at the Language end, i.e. an "ICollection(Person) Persons" in the Language entity. I would also like to have the Languages spoken by a Person at the Person end, i.e. an "ICollection(Language) Languages" in the Person entity. So I draw unidirectional associations from Person to PersonLanguageRelation and from Language to PersonLanguageRelation.

But then, some awfully named foreign keys are placed in the resulting table, of the form 
MidTable_CollectionAtEachEndName_Id, in the case of my example:
PersonLanguageRelation_Persons_Id pointing to the Id of the **Language** table and
PersonLanguageRelation_Languages_Id pointing to the Id of the **Person** table. 
Which, for my head, are very confusing, as I would prefer **Language_Id** and **Person_Id** respectively. Let alone the names of the Foreign Key pairs in the MidTable in the database which are 
FK_MidTable_FirstTable_MidTable_CollectionAtTheFirstTable_Id and
FK_MidTable_SecondTable_MidTable_CollectionAtTheSecondTable_Id

Is this naming intentional? At least the repetition of the MidTable in the foreign key names looks strange. After all we are in this table so they shouldn't be necessary.

Now, if I create unidirectional relationships from the MidTable as source to the two Entities as targets, then I lose the ICollections at the targets, I get a Person and Language reference properties in the middle entity and foreign key columns named Person_id and Language_Id. And the Foreign Keys in the database have better names, although the tables name on which they are defined could be omitted.

Would it be recommended to draw bidirectional associations? So that I have my collections and also get more sensible column names? Is there any drawback in bidirectional? I read things about performance and problems with serialization when there are loop references between entities. 

Any suggestions would be most welcome.

Best,
Alex

**Comment by msawczyn** [comment]
Alex,

Relationships technically don't have a "source" and "target", although most folks do think of them this way. They are more properly characterized as the principal or dependent ends in the relationship, with the key values stored in the class on the dependent end. In a one-to-one relationship, where it isn't obvious which is which, the programmer needs to make a design decision which is principal and which is dependent.

When creating a join class for a many to many relationship, you definitely need bidirectional associations between the two classes in question and the join class. You'll have to navigate in both directions, and a unidirectional relationship just doesn't give you the information to do that. There's some good [documentation from Microsoft](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#many-to-many) on using this design pattern for EFCore. While join classes are typically used only when there is extra data to store that only exists because of the relationship, you've correctly pointed out that EFCore requires that pattern for many-to-many associations until the team can implement that last-mile parity with EF6.

Hope that helps.

**Comment by alprinias** [comment]
Thank you very much for the answer, it really helps. It certainly reassured me that the "source" and "target" are not a real distinction and it gave me the idea of "defining" the dependent end where the key values are stored. And I liked the suggestion of defining many-to-many relationships through bidirectional associations.

It is still not clear what is rule for 1-1 relationships. There I also need to think of the difference between an 1-1 relationship and an Owned Type. I.e. why have a separate table to store the User information (username, password etc) for a Person and not just have teh User properties as an Owned Type in the same Person Table. For the moment, I only see the difference if there are common sets of properties for more than one entities, for example Patient and Doctor both having User fields. Since Owned Types cannot be shared between more than one entities, there we have to go with 1-1 relationships with a User entity. Inheritance is also involved there ...

Anyway, thanks a lot! Waiting for the new release! :-)

**Comment by alprinias** [comment]
Coming back to the associations and the column and foreign key names...

This is the picture of a toy model, with 4 entities
AOrder containing AItem(s), 1 to many relation, unidirectional, source AOrder, target AItem
BOrder containing BItem(s), 1 to many relation, unidirectional, source BItem, target BOrder

This is how they are translated into code
<
         modelBuilder.Entity<global::TestEDesigner.AOrder>()
                     .HasMany(x => x.AItemList)
                     .WithOne()
                     .HasForeignKey("AItem_AItemList_Id")
                     .IsRequired();
>
i.e. defined at the source Order side, with a correct navigation collectionProperty giving me all the Items and with a "strange" (for my taste) Foreign Key
and
<
         modelBuilder.Entity<global::TestEDesigner.BItem>()
                     .HasOne(x => x.BOrder)
                     .WithMany()
                     .HasForeignKey("BOrder_Id");
>
i.e. defined at the source again (now the direction is from Item to Order), with a "nice" Foreign Key but missing the collection of Items. 

Since they are both 1 to many relationships, the foreign key goes, correctly, to the many side, but it should be named after the 1-side entity name, i.e. also "AOrder_Id" in the first case as it is "BOrder_Id" in the second case. And not with the name of target_collectionOfTargetsInSource_Id, "AItem_AItemList_Id".

Hope it's clear and not bothering you!

![Capture](https://user-images.githubusercontent.com/8612300/67003418-8ec61000-f0e6-11e9-9e74-f2ab964640ed.JPG)

**Comment by msawczyn** [comment]
Foreign keys are an artifact of persistence. They only exist because we're persisting to a relational database, and wouldn't matter if we were persisting to an in-memory store, an object database, etc. And, as such, they're not something you use in your code. 

So we need to name them, and the T4 templates come up with a naming scheme. It's not perfect, and it doesn't match what other folks expect, but, in the end, it doesn't really matter, since as long as they're unique in a table context, they'll work. But one could always change how that happens in the T4 to suit.
