### ISSUE TITLE
One to many with required FK

### ISSUE THREAD

**Issue by mciprijanovic** [msawczyn/EFDesigner#111]
Project documentation says this: _"While cardinalities could technically include One or More (1..*), Entity Framework currently doesn’t directly support that. That doesn’t mean that it can’t be done, just that it has to be done with custom code (and, in fact, is on the to-do list of things to support with custom code generation in the designer)."_
Will this feature be in place soon? Like, by choosing 1 or many, fluent api is generated to support this...

**Comment by msawczyn** [comment]
It's still on the list, but not at the top ... got some bug fixes to handle first, and three branches as a WIP that we need to finish.

It's easier for you to do it than for me, since I have to make it generic. The thing to do is to create a custom container (say, derived from HashSet) that throws an exception if it becomes empty when something is removed from it. Use that container as your collection, and modify the entity's constructor to require the first entity for that container to come in at construction time.

When the designer does it, it will have to deal with custom containers for any standard container specified for the collection, or possibly even any custom container specified for the collection. That'll be tricky.
