### ISSUE TITLE
"Generate Code" stopped working

### ISSUE THREAD

**Issue by alprinias** [msawczyn/EFDesigner#119]
Please help, I moved everything in a new project, created all the sub folder structure etc, and now when I right click on the designer surface and "Generate Code" the status at the bottom of the VS window immediately says "Finished generating code from ....tt" and nothing has been generated. What might be wrong?
Alex

**Comment by msawczyn** [comment]
You may have moved things around so that the model can't find the T4, or vice versa. You can try a few things:
1. ensure the model file and matching T4 are in the same physical and project directory
2. right click the `[Model Name].tt` file in your project and choose `Run Custom Tool` from the context menu. If that works and your model and template files are in the same physical and project directory, yet you can't run the `Generate` menu command, I'd have to see your project to know more.
3. ensure the template file isn't nested; for some reason the T4 engine doesn't like that, although it really shouldn't matter
4. in `[Model Name].tt`, you'll see a line near the top with `requires="FileName=[Model Name].efmodel`; this is an alternative to the T4 and model being in the same directory. You can enter the path to the model here if needed.

That's the low hanging fruit ... nothing that any other project that uses T4 wouldn't have to worry about. Hope it helps

**Comment by alprinias** [comment]
Dear Michael,

the files are in the same physical and project directory.
However, when I right click on the tt file, the lines "Run Custom Tool" and "Debug T4 Template" are missing from the pop up menu, they are there in my old project. As if the tt file is not recognized.

What might have caused this?

**Comment by alprinias** [comment]
I found it. Comparing my old (working) project and the new one, I saw that in the properties of the new tt file the property "Custom Tool" was empty, whereas in the old project it was "TextTemplatingFileGenerator". As soon as I put that in the new one, the pop up menu items "Run Custom Tool" and "Debug T4 Template" showed up and the "Generate Code" worked. 

Thanks for your help!
