### ISSUE TITLE
INotifyPropertyChanged on entity property

### ISSUE THREAD

**Issue by ANM86** [msawczyn/EFDesigner#126]
With one of the latest versions it seems that "ImplementINotifyPropertyChanged" has becom an new option on entitiy properties. So far I remember right, it was only a option on the entity before. However, this new option the table columns is now set to false, so I'm not sure if it the best way to set false as default value if the entity has declared this option as true. Now I have to go through all columns and set the option to true manually. Note: This does only affect existing entity properties. New created ones seems to inherit the value from the entity's option.

**Comment by msawczyn** [comment]
That property is designed to be an override of the option on the parent entity and should reflect the parent's value unless it's changed by the user. If it's not doing that, it's a bug. I'll take a look; if it's not behaving correctly, that'll be a fix in the next release.

**Comment by msawczyn** [comment]
I've verified that the override in the entity properties does indeed work correctly. 

I understand your comment that, for existing models, you had to go through and reset the various property values to `true` when the entity was set to `true`; that's an unfortunate side effect of how tracking properties work in the Microsoft Modeling SDK.

The explanation is kind of long, but on the plus side it's only something you ever have to do once; once set it stays where you want it. And it's only ever an issue when 1) the model was created prior to the override being available at the property level, 2) the value at the entity level is set to `true`, and 3) it's the first time the model is opened after the feature became available. The property NotifyChanged values are all set to their default (`false`) and are flagged as overrides. The problem is that the tool doesn't have a good way to know that this is the first time the model has been opened after the feature became available.

Sorry for the confusion and bit of extra work, but having this override is valuable for a good number of use cases, and it shouldn't cause an issue moving forward.
