### ISSUE TITLE
Changes when opening a .efmodel file

### ISSUE THREAD

**Issue by danisss9** [msawczyn/EFDesigner#130]
Hello,

I have one quick question, every time I open a .efmodel file on visual studio it seems to make some changes to the file, even if i din't change anything in the model. It's always the same lines and it appears to be generating some random IDs. 

This does not affect the use of a tool but creates constant conflicts in Git. Is this something that can be fixed? [Example Image](https://i.imgur.com/hOt62I3.png)

Best regards!

**Comment by msawczyn** [comment]
The behavior you're seeing comes from the Microsoft Modeling SDK; try as I might, there really isn't anything that can be done.

What I have found, though, is that if you just open the file to look at it (and don't save it), you should be fine. The generalizations are recreated for some odd reason, which is why you see their guid identifiers change. 

Sorry I can't be of any more help.
