### ISSUE TITLE
VS 2017 assembly referenced on VS 2019 (v.16.4.2) setup

### ISSUE THREAD

**Issue by mmarinchenko** [msawczyn/EFDesigner#136]
While creating #135 issue I noticed a warning which states about Modeling SDK 15.0 assembly reference despite the fact I use VS 2019. I have no VS 2017 installed for now.

![Warnings](https://user-images.githubusercontent.com/21952330/71765119-6940e980-2f12-11ea-8989-29bdb94e1ac0.png)

**Comment by msawczyn** [comment]
There was a tool version that was accidentally released with the wrong assemblies linked. It's correctly a warning, as it doesn't have any negative effects, but it impacted VS2017 users rather than VS2019 users. It's been corrected.

Visual Studio SDKs ship with older assemblies versioned to the VS shipping version number for backward compatability. Typically, a binding redirect in the extension's configuration takes care of that. Note that, starting at 2.0, VS2017 won't be supported any longer, so that bit of complexity will be a thing of the past.

**Comment by mmarinchenko** [comment]
Ok, I see.

Thanks for the answer!
