### ISSUE TITLE
Migration Issue with EF Core 3.0

### ISSUE THREAD

**Issue by MattEvansA45** [msawczyn/EFDesigner#139]
I'm struggling to get an initial migration to work with EF Core 3.0.  

I get the same scenario as previous raised in issue #83 

On trying to create an initial migration i get the error message 
`Unable to create an object of type 'DataPlatformManagerContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728`

I have tried creating an empty constructor in as suggested in the comments but this hasn't worked for me and i continue to get the same error message.

```
using Microsoft.EntityFrameworkCore;
namespace DataPlatformManager.Context
{
    public partial class DataPlatformManagerContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public DataPlatformManagerContext() { }
    }
}
```
Any suggestions?

Many Thanks

**Comment by MattEvansA45** [comment]
this is the verbose error messgae 
```
Using assembly 'DataPlatformManager'.
Using startup assembly 'DataPlatformManager'.
Using application base 'C:\Users\xxxx\Source\repos\DataPlatformManager\DataPlatformManager\bin\Debug\netcoreapp3.1'.
Using working directory 'C:\Users\xxxx\Source\repos\DataPlatformManager\DataPlatformManager'.
Using root namespace 'DataPlatformManager'.
Using project directory 'C:\Users\xxxx\Source\repos\DataPlatformManager\DataPlatformManager\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding application service provider...
Finding IWebHost accessor...
No entry point was found for assembly 'DataPlatformManager'.
No application service provider was found.
Finding DbContext classes in the project...
Found DbContext 'DataPlatformManagerContext'.
Microsoft.EntityFrameworkCore.Design.OperationException: Unable to create an object of type 'DataPlatformManagerContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
```

**Comment by msawczyn** [comment]
Hmm. Since you say you added a default constructor, it's hard to pinpoint just what might be the problem. That usually takes care of that particular error message; you might get other messages if you haven't specified the storage mechanism (sqlserver, in-memory, etc.) or haven't referenced the appropriate packages, but not that one.

You might want to take a look at the the project's test code at https://github.com/msawczyn/EFDesigner/tree/master/src/Testing . While normally I don't add the migrations to the test projects, I've gone ahead and added them for each of the projects (except for the .net standard projects) and run them. The only custom code added is in the `DbContext` partial, and there I've added a default constructor and a `CustomInit` to specify storage location (sqlserver in this case). Maybe you'll see something that you're doing differently that's causing the issues. At the very least, you'll have a solution you can poke at to see if you can break it by using your patterns.

Sorry I couldn't help more right out of the chute.

**Comment by msawczyn** [comment]
Just a thought ... is the generated DataPlatformManagerContext in the DataPlatformManager.Context namespace? The code for the partial you show is. If the generated code isn't, then you've just defined a new class.

**Comment by MattEvansA45** [comment]
Thanks for the reply Michael
I found another post on a message board about issues with EFCore migrations a suggestion to create the following class. Which i did and it appears to have worked :)

Thanks
Matt
```
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace DataPlatformManager.Context
{
    public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<DataPlatformManagerContext>
    {
        public DataPlatformManagerContext CreateDbContext(string[] args)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile(@Directory.GetCurrentDirectory() + "/appsettings.json")
                .Build();
            var builder = new DbContextOptionsBuilder<DataPlatformManagerContext>();
            var connectionString = configuration.GetConnectionString("DatabaseConnection");
            builder.UseSqlServer(connectionString);
            return new DataPlatformManagerContext(builder.Options);
        }
    }
}
```
