### ISSUE TITLE
Drag onto Designer not working as expected

### ISSUE THREAD

**Issue by BLSully** [msawczyn/EFDesigner#140]
Just getting started with EF Designer in a .NET Standard 2.0 project targeting EFCore 3.1.1in VS2019 16.4.3 running in raised privileges.

Trying to import some EF6 (6.4.0) classes from a previous project targeting 4.5.2.

I cannot drag on the designer from any source. Tried dragging .cs files from Solution Explorer and Windows Explorer. Tried dragging .dll containing my EF6 context/classes from Windows Explorer. They all show a "prohibited" cursor as I drag over the designer. No errors, just a prohibited icon.

- I attempted to drag a temporary entity from the toolbox into the designer pane to see if the designer needed to be "non-empty" for the drag to work, but that did not seem to change anything. 
- Also tried generating the temporary entity/context and tried dragging again with no change.
- Also tried restarting VS with no change

Is there some configuration step I may have missed? Trying to work through the documentation to see if it's my fault or a bug, but seems unclear to me.

**Comment by msawczyn** [comment]
Thanks for the report. I can't reproduce what you're seeing with the current version (v1.3.0.12) of the designer. I'm able to dragdrop both source code and assemblies from Explorer. And there's nothing configuration-wise that you need to do to make things happen, so no worries there. The only criteria for whether you can drop something onto the designer is that the thing you're dropping is a text item and it names a file existing on your system (Dsl.csproj:Custom Code\Partials\EFModelDiagram.cs):
```
      private bool IsAcceptableDropItem(DiagramDragEventArgs diagramDragEventArgs)
      {
         IsDropping = (diagramDragEventArgs.Data.GetData("Text") is string filename && File.Exists(filename)) || 
                      (diagramDragEventArgs.Data.GetData("FileDrop") is string[] filenames && filenames.All(File.Exists));

         return IsDropping;
      }

```

The assembly parsers are currently being reworked to enhance them based on some of the changes that have come up in EF3, so you can expect to see that published soon. It sounds, though, like the dragdrop processing is where you're seeing the issue, not the parser. There was a problem quite a few versions back with .NET Standard projects, but that's been resolved for quite a while as the SDK-project-style tooling in Visual Studio has improved.

Please check that you have the most current version of the modeling tool, and please try to do the same actions with class library projects that aren't .NET Standard projects. It doesn't matter if they're fully loaded for compilation (have the right nuget packages, etc.) since we just want to see if there's a dragdrop issue. Hopefully we can get you back in the game with the designer.

**Comment by BLSully** [comment]
Thanks for the detail. I'll give it a shot in a regular .net project as soon as I can. I downloaded the extension from the VS Marketplace yesterday (1/23/20), so I'm assuming latest, though I'd be happy to build it myself too. I've got a full plate this morning, but may be able to tackle this afternoon.

**Comment by BLSully** [comment]
I've given this a shot now in a few different variations. In all cases I did exactly the same steps:

1. Project => Add => Add New Item...
2. Entity Framework Visual Editor (left at default name). Click Add
3. Drag a class file from Windows Explorer onto the editor. Contents of class:

```
public class DragDrop {
  public int Id { get; set; }
}
```
In all cases I get a prohibited icon still. No error messages or indication it's doing anything other than not letting me drop.

- Existing .NET Core 3.1 project.
- New .NET Core 3.1 project.
- New .NET Framework 4.7.2 project
- Existing .NET Framework 4.6.2 project

I can build entities and relationships just fine with the editor, so it must be something about my VS install or Windows that's preventing me from drag/dropping? Dunno. Dev workstation is about 2 months old (so VS2019 is about the same). Nothing terribly different from any other ASP.NET-centric install. I'm not the type to install a bunch of extensions typically, but I like the graphical designer for doing the initial heavy lifting of setting up new structures. I did have the Xamarin extensions installed but uninstalled all that as I'm unlikely to use it and issue still persisted.

Open to doing a Zoom screenshare if that would help at all.

**Comment by msawczyn** [comment]
Had a thought ... resetting the toolbox has helped solve a handful of toolbox-related problems. Give it a try -- https://devdept.zendesk.com/hc/en-us/articles/217842718-Resetting-Toolbox-and-Clearing-the-Toolbox-Cache

**Comment by cdru** [comment]
@BLSully Are you running Visual Studio as Administrator? Permissions/UAC likely is the reason if so. 

I normally run VS as admin for easy attaching to the system processes for debugging purposes. I wasn't able to drag a file or compiled assembly from Explorer on to the designer canvas. I too was getting the prohibited cursor (circle with diagonal slash).

Two workarounds that worked for me: 
a. Don't run VS as admin. Close VS, uncheck Run as Adminstrator from the shortcut, and and then restart VS allowed me to drag and drop from Explorer.
- Run another program as Administrator that has a File->Open dialog box. Notepad works well. Open the Open File dialog box, browse to your source file, and drag from the dialog into VS. 

I couldn't find a way to run Windows Explorer as admin under Windows 10. The several suggestions I found were from the Windows 7 era and appear to no longer work the same under an up to date Windows 10 install. I didn't spend much time on it though.

All that being said, I WAS able to drag from VS Solution Explorer on to the canvas while running as Administrator. I had initially tried one specific source file that just always threw an unspecified error. Once I figured out the the UAC Run as Administrator issue above, I went back and tried a different source file and it was working correctly, even running as Administrator. 

Hope that helps track down a work around, or at least identified why the issue was occurring.

**Comment by BLSully** [comment]
Ah, that was it. I do run as Admin as well to attach to IIS for debugging.

I'd mark this closed, and the solution for future people running into this
is "VS running as Admin".

The notepad workaround takes care of the "no elevated Windows Explorer"
issue.

Thanks much, Brendan

**Comment by msawczyn** [comment]
@cdru  Thanks for the info!
