### ISSUE TITLE
Errors in error list window persist after they are fixed

### ISSUE THREAD

**Issue by Falthazar** [msawczyn/EFDesigner#16]
Any errors due to validation do not disappear even after they are fixed.
They also do not show the project or file:
![image](https://user-images.githubusercontent.com/19520197/44301897-28304100-a2ed-11e8-949f-0ed19db3d264.png)

**Comment by VeXHarbinger** [comment]
Till it's resolved, what manual steps can we take to flush this out of the log/memory.  It gets a bit confusing.  Oh and also a BIG thank you for all your diligent efforts!

**Comment by msawczyn** [comment]
You're more than welcome!

With your comments in mind, I can see how that can be a real drag on the user experience. Digging around in it, though, it appears that the way I added those error entries ("Tasks", in Visual Studio parlance) is _exactly_ wrong -- there _isn't_ a way to get rid of them. Being that the designer is supposed to make your life easier, that's just wrong.

And it's ratcheted up my priority for fixing this significantly. It'll be the next release, and will hit quickly.

Thanks to the both of you for making me more aware of the problem, and also for the nice words.

**Comment by msawczyn** [comment]
Fixed in v1.2.4

Errors and warnings that used to persist (and were unremovable) are now output in their own pane of the output window (rather than the error window). Other validation errors and warnings can be removed by validating the model, either manually (via the context menu) or automatically (when loading or saving).
