### ISSUE TITLE
Enhancement - Stereotype to convert a class into enum

### ISSUE THREAD

**Issue by IoTFier** [msawczyn/EFDesigner#185]
Hi @msawczyn,

Unless it already exists, will it be possible for an entity created from a class (drag/drop) to convert to an enum ? 
I couldn't find any property in the properties window to apply as such.

Thank you

**Comment by msawczyn** [comment]
This really doesn't make sense to me. They're two completely different things. The only possible class structure that would work would be a static class that only contains a set of `const public int` (or some other legal enum value type) and nothing else in the class.

**Comment by IoTFier** [comment]
So, does it mean, in reference to #150, for all reference tables that are generated as classes using "dotnet ef dbcontext scaffold" I will have recreate them as enum when working with .efmodel in EFDesigner ?

I also have another schema design where a good 30+ tables are designed using class diagram.
I am planning to bring them in EFDesigner world by dragging generated .cs files.

That's where I thought it would be great to have a way to either stereotype or recreate those entities to create enum(s).
Not sure, if I am communicating the potential need (may not be feasible) clearly.

**Comment by msawczyn** [comment]
Yes. enums aren't persisted in EF as tables; they're persisted as numeric values. The enumeration value's name isn't anywhere in the persistence mechanism (e.g., the database) since it only has meaning in the code. Note how, in the designer, you don't have an association to an Enum. Rather, a property in a class can be an enum type, just like it can be a string or Int type.

The semantics are different. You can't guarantee that some string value (Name, for example) will have a unique numeric counterpart (like Id) in a database table. You can in an enum. There is no equivalence - an enum is just a shorthand way of creating a name for a group of values that the compiler will enforce where as a class is something much bigger.

I believe I understand what you want to do, but you'll need to rethink your design since there's a fundamental disconnect between the way you want it to behave and the way ORMs work.
