### ISSUE TITLE
Abstract/inherited/TPC =code still there for abstract class

### ISSUE THREAD

**Issue by ddewaleffe** [msawczyn/EFDesigner#20]
Context: trying to see how to adapt usage of the tool for use with existing stuff (base classes provided by a internal framework)...

Created a model with an abstrat class AuditEntity that has Id/ChangedOn/ChangedBy properties.
Have classes in my model inherit from this.
Chose TPC for inheritance mapping...

 1. Yet there seems to be a dbset for this abstract class [I did not expect this] .
 
 2. When I create an new E_Application and do savechanges(), EF apparently tries to cast my E_application to an AuditEntity and fails. 

I do not really know if the two symptoms are linked or separate issues or just wrong expectations/modeling by me...

![image](https://user-images.githubusercontent.com/1861106/44953794-90a82200-ae98-11e8-9c5b-d3ddfb76f532.png)
![image](https://user-images.githubusercontent.com/1861106/44953796-a4ec1f00-ae98-11e8-9c45-b0b3e0b231d7.png)
![image](https://user-images.githubusercontent.com/1861106/44953829-9fdb9f80-ae99-11e8-9a8c-99eb1263a7e6.png)
![image](https://user-images.githubusercontent.com/1861106/44953909-dd8cf800-ae9a-11e8-9eab-059242e61f0f.png)

**Comment by msawczyn** [comment]
Thanks for the question. 

When you use `Table-Per-Concrete-Class` inheritance strategy, you still get a` DbSet` for the abstract classes in the context ... you just don't get tables. If you take a look at the database that would be created from the migrations for your model, you won't see an `AuditEntity` table there. So that part of the behavior is correct.

When you said _"EF apparently tries to cast my E_application to an AuditEntity and fails,"_ that concerned me. Your model showed that `E_application` derived from `AuditEntity`; that cast can't fail. And I can't think of why Entity Framework would want to do that cast anyway. 

Looking closer, I see that you have what looks to be a typo in your namespaces. `AuditEntity` is in the `Datalayer` namespace, but `E_Application` is in the `DataLayer` (note the capital 'L') namespace. Now that shouldn't be a problem, but it does turn out that the current code generation via the T4 templates doesn't handle namespace changes very well. I usually just set the namespace at the designer level and don't change it on a per-class basis, but it's certainly an OK thing to do. So that's a fix that needs made.

Thanks for the catch!

**Comment by msawczyn** [comment]
@ddewaleffe - can you give the 1.2.5.1 release candidate build at https://github.com/msawczyn/EFDesigner/raw/master/dist/Sawczyn.EFDesigner.EFModel.DslPackage.vsix a try? It should have the fix for the namespace issue and, since you've got a sufficiently complex model, I'd really appreciate your trying it out.

**Comment by ddewaleffe** [comment]
Thanks for taking the time to look at this.
Your explanation confirms what I expected.... Looks like I missed a place
with l in place of L when I spotted the NS difference. Will look at my
model again....
And I will try your new version on it also... But only at the end of the
day....

D.

BTW, what is the feature that requires the installation to run elevated? I
seem to remember older releases did not require this ?

**Comment by msawczyn** [comment]
Thanks for giving it a spin when you get a chance.

It's the ability to extend the code via MEF that required the change to elevated permissions. That appeared in v1.1.0

Cheers!

**Comment by ddewaleffe** [comment]
I did try out the version you sent me...
It directly trigger a source error due to my typo... After fixing that I
had working tests again... Still simple but working...

Thanks a lot.
D.

**Comment by msawczyn** [comment]
And thank _you_ for finding the namespace problem.
