### ISSUE TITLE
EFCore 5: Relation to Abstract Class Results in Compiler Error

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#239]
Hello Michael,

great to see that you have a preview for EFCore 5 support available now - so I directly gave it a try! :-)

Everything looks good on first sight except one compiler error I get when there is a relation to an abstract class (tested with preview 2). I've created a minimal example for you to try here:
[EFDesignerCoreTest.zip](https://github.com/msawczyn/EFDesigner/files/5577944/EFDesignerCoreTest.zip)

By the way, a bit disappointing that unidirectional many-to-many relations are not yet supported in EFCore 5, but I know that's not on your side. ;-) I just expected that they completed all the many-to-many stuff in EFCore now...

Thanks for all your work
Andreas

**Comment by msawczyn** [comment]
Thanks for the repro file. I'll go through it tonight.

**Comment by ab-tools** [comment]
Thanks, Michael, just let me know if I can be of any further testing help! :-)

**Comment by ab-tools** [comment]
Michael, is that issue considered addressed in preview 3 already?

I see that you added a sentence `Setter for EntityAbstract EntityAbstract was not created because it's abstract. This must be set before saving.` in code now which does not exactly help with the compiler error problem. ;-))

Basically no "EntityRelated" class instance can be created without providing an instance of an implementation of "EntityAbstract" as it's otherwise unknown which implementation should be used.

Is there a way to tell EFDesigner that?

I see that in the 2.x version of EFDesigner it just skipped the instantiation of related abstract entities.

Best regards and thanks
Andreas

**Comment by msawczyn** [comment]
Yes, you're correct in that the assignment can't be made, but the lack of a concrete class isn't something we necessarily want to warn about since it can be corrected in different ways, all up to the developer. We don't want to generate bad code, but we don't necessarily prevent what may or may not be mistakes in the design, since there are an uncountable number of things the developer can do wrong, depending on the circumstances. The code, as generated, compiles and is correct, but isn't necessarily complete since the modeling might not yet be complete. That will show up at runtime.

The generated comment, though, can be improved, and I've done that. It's now

`Assignment of required association <class.property> was not generated because <class> is abstract. This must be assigned with a concrete object before saving.`

Hopefully that makes it clearer what's going on.

**Comment by ab-tools** [comment]
Thanks for your really quick reply, Michael!

The main problem was that it was not a comment (so not proceeded with `//`), so instead of 1 compiler error I got 10 now. ;-)

But I understood you changed the line to a comment (proceeding it with `//`) now?

**Comment by msawczyn** [comment]
Yes. That'll be in the release version, hopefully out today.

**Comment by ab-tools** [comment]
Thanks a lot, Michael, this is looking good now to me in your latest build!
