### ISSUE TITLE
VS2017: The type initializer ... threw an exception

### ISSUE THREAD

**Issue by xemage** [msawczyn/EFDesigner#26]
My VS2017 Community installation is crashing when trying to save a .efmodel
I have an EFcore class library project and added an EFModel, then changed the Entity Framework Version on the .efmodel to EFCore.
VS is already crashing when I try to select the Entity Framework Package Version.
When I ignore that and leave it on "Latest" then VS is crashing when I add an Entity and try to save the .efmodel file.

Following are the error log files. It looks like it doesn't find System.Net.Http

[MSBuild_pid-4104_7d49ee7c2a2445fdb59f10eb992466b6.failure.txt](https://github.com/msawczyn/EFDesigner/files/2459703/MSBuild_pid-4104_7d49ee7c2a2445fdb59f10eb992466b6.failure.txt)
[VsProjectFault_2e747c55-d05a-43a3-9498-3281a0f85deb.failure.txt](https://github.com/msawczyn/EFDesigner/files/2459704/VsProjectFault_2e747c55-d05a-43a3-9498-3281a0f85deb.failure.txt)
 
Additional info:
I had to install English language as it is a Swiss system and I first got an error about the language which is gone now.
Also I have to warnings stating
Cannot find a schema that defines target namespace 'http://schemas.microsoft.com/dsltools/EFModel'

**Comment by msawczyn** [comment]
Thanks for the report. I've been digging into this, and it appears that we're running into a reported bug in Visual Studio (https://developercommunity.visualstudio.com/content/problem/296293/vs2017-1575-ignores-the-hintpath-and-take-the-syst.html). I'm working to see what can be done to force the compiler to bind to the correct assembly version, but haven't come up with a solution yet. Nor have I gotten a workaround.

At compile time a warning is emitted indicating that there are version issues with System.Net.Http that can't be resolved, but that hasn't caused any reported issues on anyone's installation ... until now, of course. So it's clearly time to resolve the warning since it's become critical.

A while back I did have an issue with non-English systems that couldn't find the Microsoft pluralization service, but that was easily resolved. Do you have any notes as to what the problem was with your configuration before you added the English language module? I'd like to get that resolved as well so that others won't have to modify their installation to support the extension, or at the very least document it as a pre-requisite if it is truly a dependency.

Thanks again!

**Comment by msawczyn** [comment]
Re-reading your post, you should be able to work around the initial problem by avoiding the code that depends on System.Net.Http -- don't use the extension's built-in NuGet package manipulation. That's the only thing that cares about network access.

In the EFCore project, add a model and set `Install Nuget Packages On Save` to `false`. Install the EFCore packages as you normally would (likely you've already installed them) and you shouldn't see the issue.

Please let me know if that gets you over the hump while I work to sort this out.

**Comment by xemage** [comment]
Thanks for your feedback.
As you said I'm able to work with the model by deactivating "Install Nuget Packages On Save" and install them manually.
Unfortunatelly I didnt take a screenshot of the error rebort before installing the english language package but I remember it stated something like "... swiss german (de-ch) is not supported". I wasn't surprise about that though.

**Comment by msawczyn** [comment]
This should now be fixed in 1.2.6.12. Would you be willing to install that from https://github.com/msawczyn/EFDesigner/raw/master/dist/Sawczyn.EFDesigner.EFModel.DslPackage.vsix to see if it did for you?

Changelog for that release is:
   - Bugfix to remove unnecessary permission requests to push attributes down when deleting leaf nodes in an inheritance tree
   - Fix to workaround Visual Studio pulling in the wrong System.Net.Http reference. (See https://developercommunity.visualstudio.com/content/problem/296293/vs2017-1575-ignores-the-hintpath-and-take-the-syst.html)
   - Add EFModel.xsd to Visual Studio schema cache in order to avoid editor warnings for missing schema
   - Fixed template issue for non-English-language systems (where Microsoft Pluralization Service is unavailable)

**Comment by msawczyn** [comment]
Fix is in v1.2.6.12 and available on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner) and in the current repository.
