### ISSUE TITLE
Expose setter for Navigation properties by default

### ISSUE THREAD

**Issue by MisakaMikoto-35c5** [msawczyn/EFDesigner#279]
Sometimes I must set some ICollection props to null, but I can't find "Setter Visibility" on Navigation properties.

**Comment by msawczyn** [comment]
That's by design. If you want to null out a collection class that holds a navigation property, I'd suggest creating a method to do so in the entity's partial file. Although I would also strongly suggest you not do that; clearing the contents is perfectly valid, but nulling out the property can have unforeseen consequences.
