### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by mciprijanovic** [msawczyn/EFDesigner#307]
Hi Michael, since Visual Studio 2022 Preview is already available, and general release will happen in November, do you have in plan to adjust the tool for it? I tried to install it in VS 2022, but it is not available in the extensions list.

Best regards. 
Milos.

**Comment by msawczyn** [comment]
It appears that there are a good deal of changes needed to update an extension to VS2022, due to changes such as moving to a 64-bit environment, total reliance on package references, etc. I've been hoping it would be easier, but not so. And there are no docs yet on how to update a modeling sdk project, so it's taking a bit longer than I had hoped.

TLDR: it's a WIP <grin>

**Comment by Mr-Pearce** [comment]
Is there an ETA for this update?
The Release of VS 2022 is on November 8. and i would love to Upgrade both. 😉

**Comment by msawczyn** [comment]
Now available in preview at https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner2022
