### ISSUE TITLE
How to import model/tables From existing Database 

### ISSUE THREAD

**Issue by fasteddys** [msawczyn/EFDesigner#321]
Hello Michael, I am trying to two things. I looked up the documentation and was not able to find the steps, can you please share some help.

- [ ] How to `import` an `existing database`/datamodel model in your diagram, then generate code/models/entities.
- [ ] Be able to `refactor `some of the tables _to_ `inheritance tables` - this seems unique to your tool. Inheritance is still not well understood when it comes to the Database tables and your tool solves this problem.

**Comment by msawczyn** [comment]
The designer doesn't support reverse engineering of an existing database, but there are a tools that will do that for you. In VS2022, it's built in. Once you have that, you can compile and drag/drop the assembly onto a blank design surface to add it to the designer.

The VS2022 version of the designer does a much better job of this, if that's an option for you. Not much going on with the VS2019 version at this point, due to limited resources.

**Comment by msawczyn** [comment]
Regarding inheritance, just add a base class and the inheritance line connecting the two. You can then drag/drop properties from the (new) derived class onto the base class. For subsequent derived classes, you'll have to remove the base class properties. We do that because you may have modified those properties (documentation, etc.) and it would be a shame to just delete those.

You will get a validation error if you try to make a derived class that has overlapping properties, to make them easier to find.
