### ISSUE TITLE
"Save as image" needs work

### ISSUE THREAD

**Issue by Olivercomputing** [msawczyn/EFDesigner#337]
Saving the diagram as an image uses an all-white background which masks all of the connectors, basically showing only entities. Not very useful as-is. I don't see any apparent way to change the background color. Please either make it set as black, or add a global model property to make it user-selectable.

**Comment by msawczyn** [comment]
Because of the way the Microsoft Modeling SDK does visual resources, the background is the one color I can't change without some risky reflection trickery. The connector lines, though, should be coming out black, at least in v4.2.4 onward (that was a fix that was put in for that version). Are you still seeing white connectors?

**Comment by Olivercomputing** [comment]
Yes, the image is usable now, thanks!
