### ISSUE TITLE
Can't switch between EF6 and EFCore

### ISSUE THREAD

**Issue by TheMegaMatt** [msawczyn/EFDesigner#4]
When switching from EF6 to EFCore a error message pops informing that TablePerType is not supported by EFCore

**Comment by msawczyn** [comment]
@TheMegaMatt It's right -- currently the only inheritance strategy implemented in EFCore is TablePerHierarchy. The way validation is set up now, if you're already set to an EFCore model, new entities will be created with a TablePerHierarchy strategy. If you try to change that, it stubbornly changes it back. If you're creating an EF6 model, though, and change it to an EFCore model, it checks the entities for various limitations. If any of those restrictions are broken by anything in the current model, it displays the error message and rejects the change to EFCore.

I've been working on the documentation this week and plan to add a listing of all the validation rules enforced in the model ... that's coming up real soon now. IMHO, EFCore isn't yet ready for prime time. I tend to have serious discussions with anyone wanting to use it today. Not to say it isn't getting better, but there's just too much that isn't quite done. (The one that makes me craziest is the lack of many-to-many associations, but I don't want to get started on that right now.)

**Comment by msawczyn** [comment]
@TheMegaMatt One thing I do see is that, when you have an empty design surface, you should be able to switch to EFCore without having to change the inheritance strategy yourself. Since there are no entities, there are no negative effects to the change, and the tool should just do it and be quiet about it. I'll make that change -- since it's not a show-stopper, I'll hold off on releasing a new version until other things pile up, though.

**Comment by msawczyn** [comment]
Closing based on the above.
