### ISSUE TITLE
Generate diagram from DB

### ISSUE THREAD

**Issue by LucaGabi** [msawczyn/EFDesigner#44]
Can this be used to generate the initial diagram from an existing database providing a CNS?

Great project!

**Comment by msawczyn** [comment]
Thanks for the nice words. No, that isn't a planned feature. There are excellent tools available for reverse engineering a database into Entity Framework so that isn't something this tool could do better. Its purpose is, rather, generating reliable Entity Framework code starting from a clean object model.
