### ISSUE TITLE
Unable to expose Foreign Key property for associations

### ISSUE THREAD

**Issue by TondaKrist** [msawczyn/EFDesigner#55]
Foreign Key properties are not generated in code.

**Comment by msawczyn** [comment]
No, they're not; that's as-designed.

The tool is centered around object modeling, not data modeling. Foreign keys are database concepts rather than object concepts. To access associated objects you access the objects ... the foreign keys are used for persistence only, and violate the concept of "plain old C# objects" since they wouldn't be there if you weren't in a persistence context.

EF will use those to support whatever it needs to do its job, and the code generated for the DbContext does indeed specify the keys (since that's where they're important). But not in the entities.

**Comment by TondaKrist** [comment]
I understand that they are not auto generated, but it is a pitty that I can not even add them manually in partial class using EF naming convention. For some performance issues we use really often FK to attaching objects. EF designer is really nice tool, and I am personally so sad we can not use it for both object and data modeling.

**Comment by msawczyn** [comment]
I've tagged this as an enhancement request. It's possible that we can set a flag at the designer (and class level, for override) to generate those, but I'll need to look into the implications.

**Comment by Cyclonit** [comment]
I'd like to add my +1 to this issue. this enhancement would allow using EFDesigner for very resource hungry use cases.

**Comment by SimonNeP** [comment]
Hello, I stumbled across this issue but cannot find the option to generate the foreign key for the association inside my class.
The properties on class level:
![image](https://user-images.githubusercontent.com/77322496/106757801-1663c500-6631-11eb-985c-58c63d760174.png)

Maybe I'm just looking at the wrong place?

**Comment by msawczyn** [comment]
@SimonNeP -

This functionality has been there for a while, but the documentation certainly needs updated; just trying to find the time <grin>

At the model level, selecting the design surface, set `Allow Modeled Foreign Keys` to `True`. Now you can select an association and you'll see a property named `Foreign Key Property` where you can type in the name of the foreign key property. The designer will place it in the correct class. In the case of more than one identity property on the dependent class, you'll likely want to name all of the FK properties, comma-separated. The property will be added to the dependent class in the designer with a different glyph.

Note that this can't be done on a many-to-many association, since those are persisted via a join table.

If you want the names of the FK properties to show up on the diagram attached to the association, set the designer's `Show Foreign Key Property Names` value to `True`.

Hope this helps.
