### ISSUE TITLE
Impossible to have 2 EFModel in the same library

### ISSUE THREAD

**Issue by Tristan-gu** [msawczyn/EFDesigner#63]
Hi,

I've made a library with one EFModel named EFModel1.efmodel.
I generate it in some "DBContext1\sub directories" well.

Then, I 've just added a new EFModel named Context2.efmodel.
This Model is configured to generate classes in "DBContext2\sub directories".
When I generate it, all my "EFModel1" generated files disappears.

And when I re generate EFModel1, al my Context2.efmodel disappear.

Seem to have something in memory which keeps false paths for generate files.

You can test it with the attached project if you want.
[TestEFCore.zip](https://github.com/msawczyn/EFDesigner/files/3060014/TestEFCore.zip)

**Comment by msawczyn** [comment]
Thanks for the report. Multiple model files are indeed supported and work well ... the issue appears to be the new Visual Studio project format Microsoft is using, combined with .NET Standard project types. I'm looking into this now because it's something that absolutely has to be resolved as we move forward into VS 2019. There are quite a few reports on the 'net about this. 

Your sending the sample project was fabulous. There are a couple of things you might try:

- Ensure the directories you'll be generating into are part of the project. 
- Put the .efmodel files in the root of the project, rather than in a subdirectory off the project. You can generate into a subdirectory, but try not to put the models there. The new project format changes how it deals with project items that are directories.




I'll update here as I learn things.

**Comment by msawczyn** [comment]
The issue you're running into is the cleanup code that runs during generation. 

The code generator is essentially stateless, so doesn't know what code was in a prior run. During its analysis pass it gathers up all the files it needs to generate, and writes them after analysis and generation. First, though, it culls out the files in the project that have the same suffix (e.g., ".generated.cs") that it knows it _won't_ be creating during this run. That allows the programmer to remove classes from the model and have the code removed during generation time.

All you'll need to do is use different suffixes for each model (e.g., gen1, gen2, etc.) to keep them separated. Keeping them in different directory groupings isn't enough since that's something the programmer can change as they work toward getting a good file structure for the project; the suffix, experience has shown, isn't often changed and, if it is, it's something the programmer remembers that they did and so expects the disruption.

I'll make sure the documentation is updated to make this more clear.

**Comment by Tristan-gu** [comment]
Hi, Thanks for your answer.
I've just renamed suffix differently for my two models and everything worked fine.

do you have an idea of 1.2.7 release date ?

**Comment by msawczyn** [comment]
Pre-release is out now! Has some VS2019 issues, but those are, unfortunately, out of my hands. Still seeing if I can work around them, though.

**Comment by msawczyn** [comment]
Closing since it's resolved.
