### ISSUE TITLE
Model Validation does not check specified Custom Interface

### ISSUE THREAD

**Issue by ANM86** [msawczyn/EFDesigner#65]
When using a Custom Interface on a Entity it errors will be shown: "Class has no identity property in inheritance chain => Event if the Interface has got a defined Key.

[EF Core 2.2 and EF Visual Editor 1.2.6.25]

**Comment by msawczyn** [comment]
I'm not entirely sure I understand the issue, but let me try to paraphrase. You've added an interface to an entity in the model via the `Custom Interfaces` property. That interface has an `Id` property, and you've removed the `Id` property from the entity in the model. When trying to save the model (or validating by another other means), the model shows the error you indicate. Did I get that right?

That behavior is as-designed. There's a couple of things going on:

- Custom interfaces are opaque to the modeler. There is no parsing or even checking to see if the interface exists in code. It's exactly equivalent to adding the interface to a custom partial for the entity class and, in fact, only available in the model to allow you to assure that any other developers working on your project are aware of the interface.
- Interfaces don't assure implementation. If the tool would indeed find the interface and see that there was an Id property, it couldn't be sure that it would be implemented (and, by convention, then be used as the identifier for the entity). The only way it really knows if an Id property exists is if it's in the model -- then it's comfortable because it will be doing the generation of the code for that property.

If I misunderstood the issue, please expand on what you're seeing and I'll be happy to check it out. Otherwise, it's behaving as planned.

**Comment by ANM86** [comment]
Thankyou for your response. You got it right. The issue is, that i tried to get arround the inheritance chain as it is supposed to be used. My "interface" in reality is a base-table class :-). So there are several of them in my application. First I tried to use the base table property as it is designed. But only TPH is implemented, so I got the result is wrong for my requirement. Using the custom interface property, allows me to generate code which fits perfectly. But now the model is not aware of that used classes and their properties.

So if there would be a possibility I could use the base table property it would be better.
It might help if the class name could be completely user defined. Then I could specify the base table here, even if the model class is not part of the model design. This would make it easier to identify the Id property of the base class.

**Comment by msawczyn** [comment]
I'm still not 100% sure what you're after, but you can always manually add the base class in the partial if you don't want to add it to the model.

**Comment by ANM86** [comment]
Yes, this is exactly what I achive, when using the "Custom Interface" property 
I use it to extend my model classes from a base class (not implementing an interface, as it i should be used). The biggest problem I'm facing is that the identy column is specified within my base class. So my model does not really know that, there is still one existing primary key existing (in the base class),  altough I've no identy column in my entities, because the model validation does not mind the base class.

First I tried to using the "Base Class" property which of course is the right one, and I think it was designed for such cases. But than I saw that it only support TPH. In my case I would need support for TPC to get it working. 

So, an solution also could be to get TPC work for EF Core. Then all properties of the base class are handeled correct during the validation.

**Comment by msawczyn** [comment]
I see what you mean. Inheritance strategies other than TPH have been discussed for EFCore for nearly 4 years now, and it appears that some changes that are being put in place for EFCore 3.0 are laying the groundwork for it happening. They haven't said when, though.
