### ISSUE TITLE
Collection associated have private setter

### ISSUE THREAD

**Issue by Tristan-gu** [msawczyn/EFDesigner#68]
Is it normal to generate a private setter for Entities collections linked ?
I found it in  this file ?

![image](https://user-images.githubusercontent.com/41323690/56279311-23d05800-6108-11e9-9713-6ea517014791.png)

Because of that, I am unable to add a linked collection to an entity.

**Comment by msawczyn** [comment]
Typically you would want private setters in navigation properties that are collections. Especially when EF generates proxies, the collections are wrapped by the change manager so it knows when new associations happen.

Rather than setting collections, the right thing to do is to add and remove items from that collection. That prompts all sorts of things that happen under the hood, like setting cascade delete behavior (in EF Core) for orphaned associations that require the principal to be set, and fixup behavior for bidirectional associations. Replacing the collection with a new collection is a Bad Thing ... none of the side effects happen.

Do you have a use case where this isn't the case?

**Comment by Tristan-gu** [comment]
OK, thank you for the explanation.
This is was me who made dirty code.

Thank you
