### ISSUE TITLE
Migration Issue with EF Core

### ISSUE THREAD

**Issue by y976362357** [msawczyn/EFDesigner#83]
Hi, I wonder does this tool support migration the model to database or not?

I looked through the document and found nothing about it.

Here is my environment

1. Project type :   .net core(class library)
2. Target Framework:  .net core 2.1
3. EF Core : 2.2.4

Following is my project file.
` 
<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.4" />
  </ItemGroup>
`

Now in my **Designer**, i have only one entity like this:
![Capture](https://user-images.githubusercontent.com/15923358/60795501-5dac7a00-a19e-11e9-9a8e-3abec7e2a938.PNG)

Here is my **Designer Propperties**:
![Capture2](https://user-images.githubusercontent.com/15923358/60795707-b5e37c00-a19e-11e9-86e7-714ced2d7153.PNG)

i have tried the following ways to migration the model to database:

1. using dotnet ef tool,but not works, here is error

![Capture3](https://user-images.githubusercontent.com/15923358/60796086-65b8e980-a19f-11e9-9e0c-53029baf73fe.PNG)

**How can i migration the model to database?**

**Comment by msawczyn** [comment]
You'll need to add a way for the migration code to create an instance of your context. It's an EFCore thing that I don't think the EF folks completely thought through, since there are conflicting priorities in what you  need to implement to make EFCore happy.

The easiest thing to do is to add a default constructor for your DbContext class in a partial. 

```
   partial class MySchool
   {
      public MySchool() { }

      partial void CustomInit(DbContextOptionsBuilder optionsBuilder)
      {
         optionsBuilder.UseSqlServer(MySchool.ConnectionString);
      }
   }

```

That should give the migration routines enough to go on.

Hope that helps.

**Comment by y976362357** [comment]
Thanks a lot, it works now.

I'm newer about EF Core, using this tool and **model first**, you should still using CLI to migration ?

Any other way can do the migration ?

I found the designer Properties window has a property named [Automatic Migrations Enabled] when i change the Entity Framework version to EF 6.

Can you explain what dose this property does in behind?

**Comment by msawczyn** [comment]
Sure. That's an EF6 feature that lets the framework do the migration so you don't have to. Kind of frowned on these days since things happen to your database without you knowing it. See https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/migrations/automatic for more information.

You can also do migrations from the Package Manager Console in both EF6 and EFCore. You'll need to ensure that the right projects are being specified (especially problematic with .NET Standard libraries), and you may need to specify whether you're doing an `add-migration` and `update-database` with EF6 oir EFCore. Try the following commands in the Package Manager Console for more information:

-  `get-help entityframework\add-migration -full`
-  `get-help entityframework\update-database -full`
-  `get-help entityframeworkcore\add-migration -full`
-  `get-help entityframeworkcore\update-database -full`

**Comment by y976362357** [comment]
many thanks.
