### ISSUE TITLE
Cannot Saving Related Data

### ISSUE THREAD

**Issue by stevewong320** [msawczyn/EFDesigner#84]
According https://docs.microsoft.com/en-us/ef/core/saving/related-data

We can save related data like this:
```c#
using (var context = new BloggingContext())
{
    var blog = new Blog
    {
        Url = "http://blogs.msdn.com/dotnet",
        Posts = new List<Post>
        {
            new Post { Title = "Intro to C#" },
            new Post { Title = "Intro to VB.NET" },
            new Post { Title = "Intro to F#" }
        }
    };

    context.Blogs.Add(blog);
    context.SaveChanges();
}
```
However, I found that the default constructor generated by EFDesigner is protected with comment: 
> Default constructor. Protected due to required properties, but present because EF needs it.

Also, the list of ICollection object is made as private set; and it will prevent this kind of Saving Related Data action. I tried to modified the generated code and make the default constructor to public and change private set to set. After that, everything work perfectly.

Therefore, I would like to report that the default constructor should be public and the ICollection object should be set; but not private set;.

Thanks!

**Comment by msawczyn** [comment]
Hi Steve,

If the default constructor is generated as protected in an entity, it's because you've indicated that at least one of its properties is required. In the example you show, I'm going to guess that `Title` is a required property in `Post`.

If that's the case, you'll see a constructor taking a string parameter to set the `Title` property, such as `public Post(string title)`. This is by design, to add a level of safety to the code.

One of the goals, of course, in generating the code via T4 was that everyone could change what the generated code did to their liking, and I get it that you want to do something different here. But for the out-of-the-box experience, I think it's best to leave it the way it is.

Regarding the collection visibility, collections have private setters to prevent replacing the underlying collection object during the entity's lifetime. That's also by design and pretty important. While I see what you're doing with the `Blog` constructor above, it's not the safest approach for code created by a tool ... especially in a team setting where you may have different skill levels working the project. Consider the situation where the collection type changes in the model; if the collections are now all, say, `HashSet` (a _much_ more efficient choice than `List` for navigation properties), the code you show above would have to be hunted down and changed, which could get messy in a large application. 

There is a change that we are putting in place for collection visibility, though, and that will be to change the visibility to `protected internal` rather than `private`. That will help make entities more testable since you'll then be able to override the collection with a mock (by making the test assembly a friend of the entity's assembly) and still get almost the same level of coding safety.

Thanks for the post and suggestions, and I hope this helps explain some of the design choices.

**Comment by stevewong320** [comment]
Hi msawczyn,

Thanks for your reply.
However, the example is from Microsoft (https://docs.microsoft.com/en-us/ef/core/saving/related-data) and I just have an inquiry that why the Microsoft Official suggested way for inserting record is not working in EFDeisgner generated code.

Thanks!

**Comment by msawczyn** [comment]
Yes, I think I see what you're asking.

The Microsoft example is focused on the capabilities of Entity Framework, but leaves out some details that makes could potentially change the quality of the example code.

- We don't know if there are required properties in any of the entities. If there are, the safest thing to do would be to have a constructor that takes those properties as parameters, strictly from a C# point-of-view rather than from an Entity Framework point-of-view. Certainly that's not required, but it's good class design.
- We don't know what type of container is intended for Blog.Posts, although it would be a good assumption that it's a List<>. Regardless, since the List<> is being created in the constructor it's a fine thing to do, since the proxy isn't created yet. 
- We don't know how Blog.Posts is defined (e.g., ICollection<Post>? List<Post>? IList<Post>?), nor the intent to allow Lazy Loading, nor whether proxy creation is enabled in the context. All those choices inform the decision on how the code should be written.

I don't fault the example writer for leaving these things out - they would complicate the code and detract from the goal of the example, which is to show _what_ Entity Framework can do and _one way_ to deal with navigation properties. But there are options. The templates that ship with the designer simply take a different approach, given that we're wanting to make code that is safe for the majority of the use cases. Knowing that we'll never be able to cover all needs is the reason the code generation is offered as T4 templates, allowing the programmer to modify how the entity and context code is written for their specific scenario.

I appreciate the suggestion for the extra configuration elements, but don't believe it would be a good idea to move that choice into the tool rather than leaving it in the T4. Putting it into the tool gives the signal that it's a good thing to change in general rather than a change that should be made upon careful consideration of the individual use case for a project.

Hope that helps.
