### ISSUE TITLE
[Question] Can I reverse engineer an existing database to build the model?

### ISSUE THREAD

**Issue by omatrot** [msawczyn/EFDesigner#85]
I would love to be able to connect to an existing database and select which tables to include in my model as I was used to with EDMX.
Is that possible?

**Comment by msawczyn** [comment]
No, that's not a feature of this tool, by design. There are quite good utilities for reverse engineering database schema into entities (Simon Hughes' [EntityFramework Reverse POCO Generator](https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator), for example), and adding that level of functionality would be a duplication of effort that would take lots of time away from enhancing the other features of the designer.

What you can do, however, is create an set of objects using that (or another) tool and then import it into the designer. Importing can be done using C# code or a compiled assembly; [documentation is available ](https://msawczyn.github.io/EFDesigner/Importing.html) for that.

**Comment by omatrot** [comment]
Thanks
