### ISSUE TITLE
Default Value "(newid())" for GUID Keys

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#87]
Hello Michael,

for a certain use case in a project I would like to use "(newid())" instead of "(newsequentialid())" as default value for the primary GUID-based key of a table.

I did not find a entity property to change the default value generation and the "Initial Value" property does not let me enter things like "(newid())".

What is the best way to change the default value generation for GUIDs accordingly using EFDesigner?

Thanks in advance!
Andreas

**Comment by msawczyn** [comment]
Hi Andreas,

That's created by the migration code in EF rather than by the designer. You can see a Q&A about this at  https://entityframework.net/knowledge-base/47483679/entity-framework-uses-newsequentialid---for-guid-key). 

Digging around for other discussions, it appears to consensus is to change the migration code manually (info in those articles). There's nothing the designer can do for that since it's a migration thing rather than an entity definition thing.

**Comment by ab-tools** [comment]
Hello Michael,

again, thanks for your quick reply!

So just that I got it correctly (not too experienced with the Entity Framework yet to be honest ;-) ), the "OnModelCreating" method is not generated by your tool - is that correct?

Because as I would understand it correctly adding a ".HasDefaultValueSql("NEWID()");" to the GUID property would be the thing that is needed to force a random GUID instead of this pseudo sequence one.

Therefore, if this file would be generated by your tool it might be possible to add a property to the model allowing the user to choose the default SQL value to be filled accordingly with a custom value like "NEWID()".

Thanks again
Andreas

**Comment by msawczyn** [comment]
Hi Andreas,

Sorry for the long delay in getting back to you on this. 

Yes, we do generate the `OnModelCreating` method. I understand what you're requesting in that generated code, but I worry that it could be the beginning of a slippery slope of complexity, especially when setting database defaults for non-scalar properties. 

What you could do, which is currently supported, is make the change in your code via the partial methods provided as hooks to `OnModelCreating`. If you look at the generated code, you'll see two partials: `OnModelCreatingImpl` and `OnModelCreatedImpl`; the first is called at the beginning of `OnModelCreating`, the second at the end. 

For what you're after, you can implement the `OnModelCreatedImpl` in a partial for your context class and modify the model however you wish. That will be retained between code generations, since it's in your code, not the generated code.

You do raise an interesting point about how defaults are currently generated. Right now, we set them in the objects's constructor only. While that shouldn't change, we can also set them in as database generated defaults. I'd only do that for scalar properties and strings -- anything that can be legally put in the `Initial Value` editor in the property window -- but it's an idea I'll investigate to see if there are any drawbacks.

Thanks!

**Comment by ab-tools** [comment]
Hello Michael,

first thanks a lot for getting back to me on this!

What I'm doing at the moment is setting the "Identity Type" of all entity classes to "Manual" and creating a second partial class for each entity class with a single method:
```
partial void Init()
{
        Id = Guid.NewGuid();
}
```

This does work, but I would very much appreciated a more integrated way to do that if this could be possible:
At the moment I always need to remember to add this additional file with the method and also e. g. rename the class if I change the entity name for some reasons.

Therefore, if you could find an way for this particular case to directly integrate it as an option into the automated code generation this would be really great! :-)

Best regards and again thanks for getting back to me on this
Andreas

**Comment by msawczyn** [comment]
Looking into this, I believe this is a change that would negatively impact the tool. The hooks available in the `OnModelCreating` code give the ability to do what you're after (and more) without adding single-use complexity, and that's always a good thing.

I'm going to close this as `Won't do` for now.
