### ISSUE TITLE
String Length not Specified Warning

### ISSUE THREAD

**Issue by ab-tools** [msawczyn/EFDesigner#88]
Hello Michael,

for every string column there is a warning shown when the "Max Length" property is left at "0".

I do understand that in most cases you do want to specific a maximum length, but as the property description itself already states "0" should be used for no max length:
I have one case in a project where I do want to allow any string length to be inserted into this column (basically the maximum length is unknown at design time). Therefore I intentionally leave this property at "0".

In fact, the warning message could even be considered wrong then as the length is specified, just as "0" - the way it should be to allow maximum length. :-)

Is there a way to let EFDesigner know that in this case the "0" maximum length is intentional and there is no need to warn about it?

Thanks in advance!
Andreas

**Comment by msawczyn** [comment]
Hi Andreas,

I know. That's annoyed me too, but the annoyance hasn't gotten to the level where it's become a priority, I suppose :-)

We'll need a way to numerically define that you want max length -- that should remain zero since changing that would break old models. But since you brought this up, I did start thinking about the idea of defaulting the value to -1 rather than zero. At code generation time, we can treat both -1 and zero as "don't give a column size" the same way we're doing with zero now, but only the -1 value will show up as a warning in the designer (assuming, of course, that you have the option to show those turned on).

Thoughts? Opinions? Alternatives?

**Comment by ab-tools** [comment]
Hello Michael,

first appreciate your quick reply and they you even thought about a solution already! :-)

In my opinion what you suggested (using "-1" as default) would be a perfect solution:
This way it stays "0" for maximum length and the warning would only appear when you keep it at "-1".

Would be great if you could implement it this way!

Thanks again for your efforts :-)
Andreas
