### ISSUE TITLE
Strange Issue - Generated code references an entity that is NOT referenced in the diagram

### ISSUE THREAD

**Issue by ravensorb** [msawczyn/EFDesigner#9]
I am running into a very string issue.  I have an EF diagram with out 14 entities, some with relationships and some without.  There is one entity that no matter what I do it always is generated with a relationship to another entity that is not showing the designer (this includes even removing it and recreating it).

What can I do to track down what is causing this?  

Using
- Visual Studio 2017
- .NET Core 2.1 project
- Windows 10 x64

**Comment by msawczyn** [comment]
Hi Shawn @ravensorb 

Huh ... that's a new one :-)

Have you ever added that class before? Is it a valid class in your project anywhere? If you're able to send me your efmodel file, I'd be happy to take a look. You can send it to michael.sawczyn [at] improving [dot] com.

**Comment by msawczyn** [comment]
I've answered this via email directly, but wanted to leave a short explanation here in case anyone else runs into this.

The tool is actually behaving correctly. The parent class in question inherited from another class that had a required association. Since that association was necessary for the parent class, it has to be obeyed for any of its derived classes, so shows up as a constructor parameter in both the parent and derived classes.
